### ISSUE TITLE
Team.generatiePanels verwijdert panelen uit de lijst

### ISSUE THREAD

**Issue by actuallyfrank** [Requinard/TeamTab#115]
Bij het uitdelen van panelen worden de panelen verwijdert uit de game waardoor ze overal weggehaald worden en opnieuw opgehaald moeten worden uit het CSV bestand.

Maak een lokale kopie van de lijst en ga hier mee werken.
Of gebruik collisiondetection(david)

**Comment by Skaj7** [comment]
gefix voor processpanels
