### ISSUE TITLE
ClientGame.registerInvalidInstruction moet geimplementeerd worden

### ISSUE THREAD

**Issue by actuallyfrank** [Requinard/TeamTab#122]
Actielijst bij implementeren:
- Voeg loggers toe op relevante plekken
- Implementeer de code
- Voeg waar nodig exceptions toe
- Schrijf javadocs inclusief auteur
- implementeer de bijhoorende unittest
- Test de methode en verbeter waar nodig
- Zorg voor 100% code coverage
- Commit de aanpassingen
- Merge en push naar master

**Comment by actuallyfrank** [comment]
Dit gebeurd wanneer de tijd om een instructie uit te voeren in de game verlopen is. De speler is op dat moment dus te laat met het doorvoeren van een instructie

**Comment by vito-corleone** [comment]
Geïmplementeerd 
Aanpassing gemaakt aan de IGame interface waarbij de parameter Player player is toegevoegd aan de registerInvalidInstruction.
