### ISSUE TITLE
Team.hasChanged moet geimplementeerd worden

### ISSUE THREAD

**Issue by Skaj7** [Requinard/TeamTab#124]
Actielijst bij implementeren:

Voeg loggers toe op relevante plekken
Implementeer de code
Voeg waar nodig exceptions toe
Schrijf javadocs inclusief auteur
implementeer de bijhoorende unittest
Test de methode en verbeter waar nodig
Zorg voor 100% code coverage
Commit de aanpassingen
Merge en push naar master

**Comment by actuallyfrank** [comment]
David zou je hier misschien wat uitleg bij willen plaatsten deze methode is onduidelijk voor ons

**Comment by Requinard** [comment]
Deze methode geeft waar als een team nog steeds in zijn originele staat is. Dit kan gecheckt worden op de volgende manieren
- De levens en de timer zijn nog op de originele waarde
- Er zijn nog geen instructions aangemaakt

Misschien zijn er nog enkele andere manieren om dit op te lossen
