### ISSUE TITLE
De unittest playertest.testGeneratePanels dient geïmplementeerd te worden. 

### ISSUE THREAD

**Issue by vito-corleone** [Requinard/TeamTab#135]
De methode player.generatePanels() is geïmplementeerd echter is hier nog geen UnitTest voor geschreven. De unittest playertest.testGeneratePanels dient geïmplementeerd te worden.

**Comment by Requinard** [comment]
Bad issue, check de style guide

**Comment by Qunfong** [comment]
Kaj heeft dit al gemaakt. Volgens hem sluiten.
