### ISSUE TITLE
Team.generateInstruction moet aangemaakt worden

### ISSUE THREAD

**Issue by actuallyfrank** [Requinard/TeamTab#137]
Speler waarvoor dit relevant is moet meegegeven kunnen worden
Nieuwe instructie moet vervolgens aan deze speler gekoppeld worden
Actieve instructies in het team moeten aangepast worden
player.generateInstruction moet verplaatst worden naar team

**Comment by actuallyfrank** [comment]
Hier liggen nog onduidelijkheden, ik zou hier graag samen maandag met de groep naar willen kijken

**Comment by Skaj7** [comment]
volgens mij werkt de logica nu, kunnen maandag nog een checken
