### ISSUE TITLE
Unittest invullen Groep 3

### ISSUE THREAD

**Issue by ubaer** [Requinard/TeamTab#148]
De unittest zijn nog leeg, deze moeten ingevult worden, het gaat om de methodes in ClientGameTest :
testReset();
testRegisterInvalidInstruction();
testProcessPanel();

**Comment by actuallyfrank** [comment]
testRegisterInvalidInstruction() staat nog als taak voor Kamil om te implementeren en te testen

**Comment by actuallyfrank** [comment]
testProcessPanel staat als taak nog voor Kaj om te implementeren en te testen
