### ISSUE TITLE
Game.subtractLives is hard gekoppeld

### ISSUE THREAD

**Issue by Requinard** [Requinard/TeamTab#23]

**Comment by actuallyfrank** [comment]
End game returned nu een lijst met de scores die het team behaald heeft. Wanneer een team af is ziet hij de prestaties van zijn eigen team en wordt hij uit de game gehaald. Hoe kan de GUI de return waarde van end game krijgen?

**Comment by actuallyfrank** [comment]
De harde koppeling is al wel opgelost

**Comment by actuallyfrank** [comment]
Nieuwe issue van gemaakt verplaatst naar 'Game.endGame voor ieder team'
