### ISSUE TITLE
Fill panels with panels

### ISSUE THREAD

**Issue by Requinard** [Requinard/TeamTab#51]
We need at least 50

**Comment by profesorfrink42** [comment]
Put panels inside panels? Nice.

**Comment by Qunfong** [comment]
Frank heeft geen reactie meer ontvangen hierover zoals op whatsapp besproken

**Comment by Requinard** [comment]
stop being a donguer bacon-senpai

**Comment by profesorfrink42** [comment]
¯\_(ツ)_/¯
