### ISSUE TITLE
De game moet weten welke speler je bent

### ISSUE THREAD

**Issue by ubaer** [Requinard/TeamTab#52]

**Comment by actuallyfrank** [comment]
Is bij het starten van de game een return van de player genoeg?

**Comment by Qunfong** [comment]
Er wordt nu een list van teams gereturned bij startgame. Moet dit dan worden aangepast zodat de player wordt gereturned? of een nieuwe methode voor player returnen ?

**Comment by Qunfong** [comment]
Nu returned de game bij het starten de speler. Kan de issue worden gesloten ?

**Comment by vito-corleone** [comment]
Qunfong commented 5 days ago
Nu returned de game bij het starten de speler. Kan de issue worden gesloten ?

Gesloten
