### ISSUE TITLE
Help feedback nodig van Team GUI

### ISSUE THREAD

**Issue by actuallyfrank** [Requinard/TeamTab#56]
Is het zo dat wanneer de game gestart wordt dat de controllers al weten welke speler ze zijn. Deze speler geeft bij de startgame in de game logica mee welke speler hij is. Deze speler wordt initialiseert in de game logica en een referentie van deze player wordt terug gegeven aan de game controller.

Is dit correct?

**Comment by Requinard** [comment]
Ja dit is zo. Het spel moet de speler initaliseren
