### ISSUE TITLE
player krijgt nog geen nieuwe instructie

### ISSUE THREAD

**Issue by actuallyfrank** [Requinard/TeamTab#57]

**Comment by actuallyfrank** [comment]
vraag aan david: Hoe, waar en wanneer worden alle instructies inclusief te panels aangemaakt? Dit is wordt namelijk nog helemaal nergens gedaan. Hierdoor kunnen we ook nog geen nieuwe instructies geven aan spelers.

**Comment by Qunfong** [comment]
Heb het weer aan david gekoppeld omdat ik nog geen antwoord zie.

**Comment by Requinard** [comment]
De team heeft aan het begin een lijst van panels. Hier wordt random een instructie in aangemaakt als dit nodig is.
