### ISSUE TITLE
Game.returnPanelsPlayer() Test

### ISSUE THREAD

**Issue by Qunfong** [Requinard/TeamTab#64]

**Comment by actuallyfrank** [comment]
Heb hem bij qunfong gezet aangezien hij de functionaliteit maakt op panels aan een speler te geven

**Comment by Qunfong** [comment]
Is nog niet af. Hier krijg ik de methode niet werkend.

**Comment by Qunfong** [comment]
wachtend op antwoord issue Kopie maken van panels uit de lijst #85
