### ISSUE TITLE
Instruction.getNewValue testen

### ISSUE THREAD

**Issue by actuallyfrank** [Requinard/TeamTab#72]

**Comment by actuallyfrank** [comment]
Wat moet dit doen Qunfong?

**Comment by Qunfong** [comment]
Voor de nieuwe ronde wordt er een nieuw panel gemaakt. Deze heeft dan ook een nieuwe instructie. Volgens mij is het zodat de nieuwe instructie kan worden gegeven aan de nieuwe panel.
