### ISSUE TITLE
Sorteren van spelers op basis van score

### ISSUE THREAD

**Issue by actuallyfrank** [Requinard/TeamTab#77]
Spelers worden gesorteerd aan het einde van de game op basis van hun score.
Deze score wordt echter nooit aangepast dus hoe kan hier op gesorteerd worden?
Score moet gelijk staan aan het aantal correcte instructies dat een speler in de game gedaan heeft.
Oplossing: Elke keer wanneer de speler een succesvolle instructie uitvoert moet de score verhoogt worden.

**Comment by Qunfong** [comment]
Ik neem dat je dan in Game.java in de methode checkInstruction(Panel changedPanel, Player player)
een player.score += 1 wil doen ? klopt dit ?
