### ISSUE TITLE
panel.instruction vraag

### ISSUE THREAD

**Issue by actuallyfrank** [Requinard/TeamTab#79]
Een panel hoeft toch eigenlijk niet te weten bij welke instructie hij hoort?

**Comment by Qunfong** [comment]
Is het niet zo dat de instructies worden gekoppeld aan de panel en dat dit vervolgens wordt op het scherm wordt gezet? want waar haalt de panel anders zijn instructies vandaan.

**Comment by Requinard** [comment]
Dit is inderdaad zo, een panel kan meerdere instructies hebben, maar weet hier niks van. een instructie weet echter wel bij ieder paneel hij hoort

**Comment by actuallyfrank** [comment]
NOG STEEDS NIET OPGELOST
